import { Command } from "commander";
// Core sending logic now lives in the shared core package (packages/core),
// not here. This CLI only calls it and formats the result for the terminal.
import { sendTelegramMessage } from "sendkit-core";

const program = new Command();

program
  .name("sendkit")
  .description("sendkit tutorial cli")
  .command("telegram")
  .description("send a telegram message")
  .argument("<chatId>", "Telegram chat ID")
  .argument("<message>", "Message text to send")
  .action(async (chatId: string, message: string) => {
    // The bot token is read here (in the CLI) because it's specific to how
    // the CLI is invoked — from an environment variable. Other interfaces
    // (e.g. an MCP server) may get the token a different way, so this
    // env-var lookup stays in the CLI, not in the shared core.
    const botToken = process.env.TELEGRAM_BOT_TOKEN;

    if (!botToken) {
      console.error("Error: Missing TELEGRAM_BOT_TOKEN env variable");
      process.exit(1);
    }

    // All validation (chatId format, message length, token presence) and
    // the actual Telegram API call now happen INSIDE sendTelegramMessage,
    // defined in packages/core/src/operations.ts, using Zod schemas from
    // packages/core/src/schemas.ts.
    //
    // This CLI no longer does manual regex checks, manual fetch(), or
    // manual response parsing — all of that used to live directly in this
    // file, but has moved to the core so it can be reused by the CLI, the
    // MCP servers, and the Skill without duplicating logic.
    const result = await sendTelegramMessage({ chatId, message, botToken });

    // sendTelegramMessage never throws (it uses Zod's .safeParse() internally
    // — see the comment block in operations.ts for why). It always returns
    // { success: true, data } or { success: false, error }, so we just
    // check `result.success` here instead of using try/catch.
    if (!result.success) {
      console.error(`Error: ${result.error}`);
      process.exit(1);
    }

    // result.data matches the shape of telegramMessageOutputSchema
    // (packages/core/src/schemas.ts): { ok: true, chatId, messageId }.
    //
    // WHY only `messageId` is printed here, not `chatId`:
    // The user already typed the chatId themselves as a CLI argument, so
    // echoing it back adds no new information. `messageId`, on the other
    // hand, is generated by Telegram and only known AFTER the message is
    // sent — printing it gives the user real confirmation/proof that the
    // message was actually delivered, not just attempted.
    //
    // General rule: print information the user didn't already have, or
    // that proves the action succeeded. Don't echo back what they just typed.
    console.log(
      `Message sent successfully (message_id: ${result.data.messageId})`,
    );
  });

program.parseAsync(process.argv);
